spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost/user_auth_template_app?serverTimezone=Europe/Warsaw&createDatabaseIfNotExist=true
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

application:
  default:
    newUserRole: ROLE_USER
    roles:
      - ROLE_ADMIN
      - ROLE_USER
      - ROLE_MODERATOR
    users:
      - username: admin
        password: nimda
        roles: ROLE_ADMIN,ROLE_USER,ROLE_MODERATOR
      - username: user
        password: user
        roles: ROLE_USER
